
# ===== SERVER =====
server.port=8080
# B\u1eadt t\u00ednh n\u0103ng hi\u1ec3n th\u1ecb tin nh\u1eafn l\u1ed7i chi ti\u1ebft ra ngo\u00e0i API
server.error.include-message=always


# ===== DATABASE =====
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===== SWAGGER =====
# Đổi đường dẫn trang giao diện Swagger (Ví dụ: localhost:8080/swagger)
springdoc.swagger-ui.path=/swagger
# Đổi đường dẫn file json chứa đặc tả dữ liệu API (Mặc định nếu cần)
springdoc.api-docs.path=/api-docs
# Sắp xếp endpoint theo method (GET, POST, PUT, DELETE)
springdoc.swagger-ui.operations-sorter=method

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# Chuỗi khóa bí mật dùng để ký mã hóa JWT (Hãy đổi thành chuỗi ngẫu nhiên của bạn)
hocviec.jwt.signer-key=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
