# ===== APP =====
spring.application.name=hocviec

# ===== SERVER =====
server.port=8080
# B\u1eadt t\u00ednh n\u0103ng hi\u1ec3n th\u1ecb tin nh\u1eafn l\u1ed7i chi ti\u1ebft ra ngo\u00e0i API
server.error.include-message=always


# ===== DATABASE =====
spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_hoc_viec_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# ===== SWAGGER =====
# Đổi đường dẫn trang giao diện Swagger (Ví dụ: localhost:8080/swagger)
springdoc.swagger-ui.path=/swagger
# Đổi đường dẫn file json chứa đặc tả dữ liệu API (Mặc định nếu cần)
springdoc.api-docs.path=/api-docs
# Sắp xếp endpoint theo method (GET, POST, PUT, DELETE)
springdoc.swagger-ui.operations-sorter=method

# ===== LOGGING =====
# Ghi log ra file (xem lại log cũ tại logs/app.log), vẫn in ra console như bình thường
logging.file.name=logs/app.log

# Thiết lập tài khoản đăng nhập thử nghiệm
spring.security.user.name=admin
spring.security.user.password=123456
